core/urls.py
from django.contrib import admin
from django.urls import path, re_path
from core import views


from .views import *

urlpatterns = [
    
    path('', views.base_core, name="base_core"),
    path('sign-in/', views.sign_in, name="sign_in"),
    path('register/', views.register, name="register"),
    path('main/', views.main, name="main"),
    path('doctor-<login>/db-patients/', views.db_patients, name="db_patients"),
    path('job-with-db-patients/', views.job_with_db_patients, name="job_with_db_patients"),
    path('doctor-<login>/postuplenie/', views.postuplenie, name="postuplenie"),
    path('doctor-<login>/db-questions/', views.db_questions, name="db_questions"),
    path('job-with-db-questions/', views.job_with_db_questions, name="job_with_db_questions"),
    path('doctor-<login>/db-diseases/', views.db_diseases, name="db_diseases"),
    path('job-with-db-diseases/', views.job_with_db_diseases, name="job_with_db_diseases"),
    path('doctor-<login>/postuplenie/db-anckets', views.db_anckets, name="db_anckets"),
    path('doctor-<login>/profile/', views.profile, name="profile"),
    path('job-with-db-anckets/', views.job_with_db_anckets, name="job_with_db_anckets"),
    path('doctor-<login>/chose-method-work-patient/', views.chose_method_work_patient, name="chose_method_work_patient"),
    path('doctor-<login>/job-with-db-epicriz/', views.job_with_db_epicriz, name="job_with_db_epicriz"),
    path('doctor-<login>/job-with-db-diagnozes/', views.job_with_db_diagnozes, name="job_with_db_diagnozes"),
    path('doctor-<login>/work-with-rules/', views.work_with_rules, name="work_with_rules"),
    path('doctor-<login>/db-symptoms/', views.db_symptoms, name="db_symptoms"),
    path('job-with-db-symptoms/', views.job_with_db_symptoms, name="job_with_db_symptoms"),
    
    path('<login>-directory/', views.directory, name="directory"),
    path('diagnos/delete/', views.delete_diagnos, name="delete_diagnos"),
    path('diagnos/add/', views.add_diagnos, name="add_diagnos"),
    path('diagnos/get/', views.get_diagnos, name="get_diagnos"),
    path('diagnos/update/', views.update_diagnos, name="update_diagnos"),

    path('symptom/delete/', views.delete_symptom, name="delete_symptom"),
    path('symptom/add/', views.add_symptom, name="add_symptom"),
    path('symptom/get/', views.get_symptom, name="get_symptom"),
    path('symptom/update/', views.update_symptom, name="update_symptom"),

    path('syndrom/getform/', views.syndrom_get_form, name="syndrom_get_form"),
    path('syndrom/delete/', views.delete_syndrom, name="delete_syndrom"),
    path('syndrom/add/', views.add_syndrom, name="add_syndrom"),
    path('syndrom/open-<id>/doc-<login>/', views.open_syndrom, name="open_syndrom"),
    path('syndrom/update/', views.update_syndrom, name="update_syndrom"),

    path('<login>-patient_records/',views.patient_records, name="patient_records"),
    path('patient_records/add/', views.add_patient_records, name="add_patient_records"),
    path('patient_records/delete/', views.delete_patient_records, name="delete_patient_records"),
    path('patient_records/update/', views.update_patient_records, name="update_patient_records"),
    path('patient_records/get/', views.get_patient_records, name="get_patient_records"),

    path('patient_records/view/<int:id>/<login>', views.view_patient_records, name="view_patient_records"),
    path('patient_records/view/<id>/<login>/del=<int:id_entry>', views.delete_treatment, name="delete_treatment"),
    path('patient_records/view/<int:id_p>/<login>/treatment-<int:id_tr>', views.view_treatment, name="view_treatment"),
    path('patient_records/view/<int:id_p>/<login>/treatment-<int:id_tr>/del=<int:id_entry>', views.delete_diagnosis, name="delete_diagnosis"),
    path('patient_records/view/<int:id_p>/<login>/treatment-<int:id_tr>/diagnosis-<int:id_d>', views.view_diagnosis,
         name="view_diagnosis"),
    path('form/<login>/del=<int:id_entry>', views.delete_form,
         name="delete_form"),
    path('patient_records/view/<int:id_p>/<login>/treatment-<int:id_tr>/diagnosis-<int:id_d>/form-<int:id_f>', views.view_form,
         name="view_form"),

    path("<login>-personal_cabinet/", views.personal_cabinet, name="personal_cabinet"),
    path("person/get", views.get_person, name="get_person"),
    path("person/update", views.update_person, name="update_person"),


    path('symrule/delete/', views.delete_symrule, name="delete_symrule"),
    path('symrule/add/', views.add_symrule, name="add_symrule"),
    path('symrule/get/', views.get_symrule, name="get_symrule"),
    path('symrule/update/', views.update_symrule, name="update_symrule"),

    path('questionary/doc-<login>/', views.questionary, name="questionary"),
    path('questdoc/add/', views.add_questdoc, name="add_questdoc"),
    path('questdoc/delete/', views.delete_questdoc, name="delete_questdoc"),
    path('questdoc/deleteall/', views.deleteall_questdoc, name="deleteall_questdoc"),
    path('questdoc/get/', views.get_questdoc, name="get_questdoc"),
    path('questdoc/update/', views.update_questdoc, name="update_questdoc"),

    path('questForm/add/', views.add_questForm, name="add_questForm"),
    path('questForm/delete/', views.delete_questForm, name="delete_questForm"),
    path('questForm/deleteall/', views.deleteall_questForm, name="deleteall_questForm"),
    path('questForm/get/', views.get_questForm, name="get_questForm"),
    path('questForm/update/', views.update_questForm, name="update_questForm"),

    path('mamdani/', views.alg_mamdani_up, name="alg_mamdani_up"),
    path('mamdani/form/', views.alg_mamdani_upForm, name="alg_mamdani_upForm"),



    path('api/patient-record/', PatientRecordView.as_view()),
    path('api/patient-record/<int:pk>', PatientRecordView.as_view()),
    path('api/single-patient-record/<int:pk>', SinglePatientRecordView.as_view()),

    path('api/doctor/<login>', DoctorView.as_view()),
    path('api/login-doctor/<login>/<password>', LoginDoctorView.as_view()),

    path('api/patient-list/', PatientListView.as_view()),
    path('api/patient-list/<int:pk>', PatientListView.as_view()),
    path('api/single-patient-list/<int:pk>', SinglePatientListView.as_view()),

    path('api/treatment/', TreatmentView.as_view()),
    path('api/treatment/<int:pk>', TreatmentView.as_view()),
    path('api/single-treatment/<int:pk>', SingleTreatmentView.as_view()),

    path('api/epicrisis/', EpicrisisView.as_view()),
    path('api/epicrisis/<int:pk>', EpicrisisView.as_view()),
    path('api/single-epicrisis/<int:pk>', SingleEpicrisisView.as_view()),

    path('api/diagnosis/', DiagnosisView.as_view()),
    path('api/diagnosis/<int:pk>', DiagnosisView.as_view()),
    path('api/single-diagnosis/<int:pk>', SingleDiagnosisView.as_view()),

    path('api/diagnos/', DiagnosView.as_view()),
    path('api/diagnos/<int:pk>', DiagnosView.as_view()),
    path('api/single-diagnos/<int:pk>', SingleDiagnosView.as_view()),

    path('api/form/', FormView.as_view()),
    path('api/form/<int:pk>', FormView.as_view()),
    path('api/single-form/<int:pk>', SingleFormView.as_view()),

    path('api/rule/', RuleView.as_view()),
    path('api/rule/<int:pk>', RuleView.as_view()),
    path('api/single-rule/<int:pk>', SingleRuleView.as_view()),

    path('api/symptom/', SymptomView.as_view()),
    path('api/symptom/<int:pk>', SymptomView.as_view()),
    path('api/single-symptom/<int:pk>', SingleSymptomView.as_view()),

    path('api/rule-symptom/', RuleSymptomView.as_view()),
    path('api/rule-symptom/<int:pk>', RuleSymptomView.as_view()),
    path('api/single-rule-symptom/<int:pk>', SingleRuleSymptomView.as_view()),
    
    path('api/selected-symptoms/', SelectedSymptomsView.as_view()),
    path('api/selected-symptoms/<int:pk>', SelectedSymptomsView.as_view()),
    path('api/single-selected-symptoms/<int:pk>', SingleSelectedSymptomsView.as_view()),
    
    path('api/selected-symptoms-doctor/', SelectedSymptomsDoctorView.as_view()),
    path('api/selected-symptoms-doctor/<int:pk>', SelectedSymptomsDoctorView.as_view()),
    path('api/single-selected-symptoms-doctor/<int:pk>', SingleSelectedSymptomsDoctorView.as_view()),

    path('api/anamesis/', AnamesisView.as_view()),
    path('api/anamesis/<int:pk>', AnamesisView.as_view()),
    path('api/single-anamesis/<int:pk>', SingleAnamesisView.as_view()),

    path('api/mamdani/doc-<login>', MamdaniDocView.as_view()),
    path('api/mamdani/form-<int:pk>', MamdaniFormView.as_view()),
]

iswork/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
]

core/models.py
from django.db import models
from datetime import  date


class PatientRecord(models.Model):
    NumberRecord = models.CharField(max_length=200, verbose_name='number record')
    FIO = models.CharField(max_length=200, verbose_name='FIO')
    Birthday = models.DateField(default = "1999-01-01", null=True)
    Sex = models.CharField(choices=[('M', 'Man'),('W', 'Woman')], max_length=200, verbose_name='sex')
    Adress = models.CharField(max_length=200, verbose_name='adress')
    Phone = models.CharField(max_length=50, verbose_name='phone')

    class Meta():
        verbose_name = 'patient'
        verbose_name_plural = 'patients'

    def __str__(self):
        return self.FIO



class Doctor(models.Model):
    #Patient = models.ManyToManyField(PatientRecord, through='PatientList') #useless
    login = models.CharField(max_length=200, verbose_name='login')
    email = models.CharField(max_length=200, verbose_name='email', default="", blank=True )
    password = models.CharField(max_length=50, verbose_name='password', default="", blank=True )
    FIO = models.CharField(max_length=50, verbose_name='last first middle name', default="", blank=True )
    Activated = models.BooleanField(default=False)
    SocialNetwork = models.CharField(max_length=50, verbose_name='SocialNetwork', default="", blank=True )
    Position = models.CharField(max_length=50, verbose_name='position', default="", blank=True )
    Department = models.CharField(max_length=50, verbose_name='department', default="", blank=True )

    def __str__(self):
        return self.login

    class Meta():
        verbose_name = 'doctor'
        verbose_name_plural = 'doctors'





class PatientList(models.Model):
    Doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    PatientRecord = models.ForeignKey(PatientRecord, on_delete=models.CASCADE)


class Treatment(models.Model):
    Record = models.ForeignKey(PatientRecord, on_delete=models.CASCADE)
    Doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    Name = models.CharField(max_length=200, verbose_name='name')
    Date = models.DateField(default=date.today())
    Note = models.CharField(max_length=5000, verbose_name='note')

    class Meta():
        verbose_name = 'treatment'
        verbose_name_plural = 'treatments'


class Epicrisis(models.Model):
    Treatment = models.OneToOneField(Treatment,on_delete=models.CASCADE)
    Referral = models.CharField(max_length=1000, verbose_name='referral')
    Therapy = models.CharField(max_length=50000, verbose_name='therapy')
    Disability = models.CharField(max_length=1000, verbose_name='disability')
    Hospitalization = models.DateField(default =date.today(), null=True)
    HospitalDischarge = models.DateField(default=date.today(), null=True)
    IsOver = models.IntegerField()

    class Meta():
        verbose_name = 'epicrisis'
        verbose_name_plural = 'epicrises'


class Diagnosis(models.Model):
    Treatment = models.ForeignKey(Treatment, on_delete=models.CASCADE)
    Doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    Name = models.CharField(max_length=1000, verbose_name='name')
    StartDiagnosis = models.DateField(default=date.today(), null=True)
    Note = models.CharField(max_length=50000, verbose_name='note')

    class Meta():
        verbose_name = 'diagnosis'
        verbose_name_plural = 'diagnostics'


class Diagnos(models.Model):
    Name = models.CharField(max_length=1000, verbose_name='name')
    Description = models.CharField(max_length=50000, verbose_name='description')

    class Meta():
        verbose_name = 'diagnos'
        verbose_name_plural = 'diagnoses'
    
    def __str__(self):
        return self.Name

    def __unicode__(self):
        return self.Name


class Conviction(models.Model):
    Name = models.CharField(max_length=1000, verbose_name='name')
    Position = models.IntegerField()

    class Meta():
        verbose_name = 'conviction'
        verbose_name_plural = 'convictions'
    
    def __str__(self):
        return self.Name

    def __unicode__(self):
        return self.Name


class Form(models.Model):
    Diagnosis = models.ForeignKey(Diagnosis, on_delete=models.CASCADE)
    Diagnos = models.ForeignKey(Diagnos, on_delete=models.CASCADE, null=True)
    Name = models.CharField(max_length=1000, verbose_name='name')
    DateForm = models.DateField(default=date.today())
    Note = models.CharField(max_length=50000, verbose_name='note')
    Conviction = models.ForeignKey(Conviction, on_delete=models.CASCADE, null=True)

    class Meta():
        verbose_name = 'form'
        verbose_name_plural = 'forms'


class Frequency(models.Model):
    Name = models.CharField(max_length=1000, verbose_name='name')
    Coef = models.FloatField()

    class Meta():
        verbose_name = 'frequency'
        verbose_name_plural = 'frequency'
    
    def __str__(self):
        return self.Name

    def __unicode__(self):
        return self.Name

class Rule(models.Model):
    Diagnos = models.ForeignKey(Diagnos, on_delete=models.CASCADE)
    Frequency = models.ForeignKey(Frequency, on_delete=models.CASCADE)

    class Meta():
        verbose_name = 'rule'
        verbose_name_plural = 'rules'
    

class Symptom(models.Model):
    Name = models.CharField(max_length=1000, verbose_name='name')
    Description = models.CharField(max_length=50000, verbose_name='description')

    class Meta():
        verbose_name = 'symptom'
        verbose_name_plural = 'symptoms'
    
    def __str__(self):
        return self.Name

    def __unicode__(self):
        return self.Name

class RuleSymptom(models.Model):
    Rule = models.ForeignKey(Rule, on_delete=models.CASCADE)
    Symptom = models.ForeignKey(Symptom, on_delete=models.CASCADE)
    Conviction = models.ForeignKey(Conviction, on_delete=models.CASCADE)

    class Meta():
        verbose_name = 'rule symptom'
        verbose_name_plural = 'rules symptom'
    
    def __str__(self):
        return self.Name

    def __unicode__(self):
        return self.Name




class SelectedSymptoms(models.Model):
    Form = models.ForeignKey(Form, on_delete=models.CASCADE)
    Symptom = models.ForeignKey(Symptom, on_delete=models.CASCADE)
    Conviction = models.ForeignKey(Conviction, on_delete=models.CASCADE)
    Note = models.CharField(max_length=50000, verbose_name='note')

    class Meta():
        verbose_name = 'selected symptom'
        verbose_name_plural = 'selected symptoms'

class SelectedSymptomsDoctor(models.Model):
    Doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    Symptom = models.ForeignKey(Symptom, on_delete=models.CASCADE)
    Conviction = models.ForeignKey(Conviction, on_delete=models.CASCADE)
    Note = models.CharField(max_length=50000, verbose_name='note')

    class Meta():
        verbose_name = 'selected doc symptom'
        verbose_name_plural = 'selected doc symptoms'

class Anamesis(models.Model):
    Treatment = models.OneToOneField(Treatment, on_delete=models.CASCADE)
    Diagnos = models.ForeignKey(Diagnos, on_delete=models.CASCADE)

    class Meta():
        verbose_name = 'Anamesis'
        verbose_name_plural = 'Anamesises'
        

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--CSS-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!--JS-->
    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->

    <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css">

    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/js/select2.full.min.js"></script>


    <title>{% block title %}Log in{% endblock %}</title>
</head>

<style>
    nav {
        background: rgb(0, 1, 57);
    }
</style>

<body style="background: linear-gradient(to left,rgb(22, 3, 38, 1),rgb(0, 49, 76, 1));">

    {% block navbar %}

    <nav class="navbar navbar-expand-lg">
        <a class="navbar-brand text-white my-0 mr-md-auto font-weight-normal" href="#">Medical Diagnostics Module</a>
        <nav class="my-2 my-md-0 mr-md-3">
            <a class="p-2 text-white" href="{% url 'patient_records' login=login%}">Patient Records</a>
            <a class="p-2 text-white" href="{% url 'questionary' login=login%}">Questionary</a>
            <a class="p-2 text-white" href="{% url 'directory' login=login%}">Directory</a>
            <a class="p-2 text-white" href="{% url 'personal_cabinet' login=login%}">Personal Cabinet</a>
        </nav>
        <a class="btn btn-outline-primary" href="/">Log Out</a>

    </nav>
    {% endblock %} {% block content %} {% endblock %} {% block footer %}
    <footer class="container pt-4 my-md-5 pt-md-5 border-top mt-5">
        <div class="row">
            <div class="col-12 col-md">
                <small class="d-block mb-3 text-muted">© 2020</small>
            </div>
        </div>
    </footer>
    {% endblock %}

</body>

</html>

core/templates/core/base_core.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--CSS-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!--JS-->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <title>{% block title %}Log in{% endblock %}</title>
</head>

<body style="background-color: rgb(210, 176, 238)">


    {% block navbar %} {% endblock %} {% block content %} {% if message %}
    <script>
        alert('{{ message }}')
    </script>
    {% endif %}


    <form action="{% url 'main' %}" method="POST">

        {% csrf_token %}


        <div class="container-fluid h-100">
            <div class="row align-items-center h-100">
                <div class="col-sm-12">
                    <div class="row justify-content-center">
                        <div class="col-3 text-center" style="background-color: white; box-shadow: 0 0 10px; position: fixed; top: 25%">
                            <h2 class="signinText" style="text-align: center;">Sign in</h2>
                            <div class="form-group" style="text-align: left;">
                                <label for="login">Login:</label> {{ form.login }}
                            </div>
                            <div class="form-group" style="text-align: left;">
                                <label class='' for="exampleInputPassword1" style="text-align: left;">Password:</label> {{ form.password }}
                            </div>
                            <div class="">
                            </div>
                            <div class="button" style="text-align: center;">
                                <button type="submit" class="mb-3 btn btn-primary">Sign in</button>
                            </div>
                            <div class="a mb-2" style="text-align: center;">
                                <a class="" href="{% url 'register' %}">Sign up</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </form>

    {% endblock %}

</body>

</html>

core/templates/core/index.html
{% extends 'core/base_core.html' %}


{% block title %}Sign in{% endblock %}


{% block content %}

<form method="POST">

{% csrf_token %}

<div class="container-fluid h-100">
	<div class="row align-items-center h-100">
		<div class="col-sm-12">
			<div class="row justify-content-center">
				<div class="col-3 text-center" style="background-color: white; box-shadow: 0 0 10px; position: fixed; top: 25%">
					<form>

						<h2 class="signinText" style="text-align: center;">Log in</h2>
						<div class="form-group" style="text-align: left;">
						  <label for="login">Login:</label>
						  {{ form.login }}
						</div>
						<div class="form-group" style="text-align: left;">
						  <label class='' for="exampleInputPassword1" style="text-align: left;">Password:</label>
						  {{ form.password }}
						</div>
						<div class="button" style="text-align:center">
							<button type="submit" class="mb-3 btn btn-primary">Log in</button>
                        </div>

					  </form>
				</div>
			</div>
		</div>
	</div>
</div>

{% endblock %}

core/templates/core/view_patient.html
{% extends 'core/base.html' %}
{% block title %}Patient view{% endblock %}
{% block content %}
<a type="button" rel="tooltip" href="{% url 'patient_records' login=login %}" class="ml-3 mt-2 h5 text-white" data-original-title="" title="">&#8592; back (Patient records)</a>

    <div class="d-flex justify-content-center mt-3">
        <div class="col-md-7 mb-1 mt-1 text-white text-center ">
            <div class="container">
                <h1 class="jumbotron-heading">Patient</h1>
                <p class="lead">You login as {{ user.login }}</p>
            </div>
        </div>
    </div>

    <div class="container mt-3">

        <div class="card">
            <div class="card-body">
                <div class="border-bottom pb-4">
                    <h4 class="card-title">{{ patient.FIO }}</h4>
                    <p class="card-text text-dark mx-2 border-bottom pl-1">Number Card: {{ patient.NumberRecord }}</p>
                    <p class="card-text text-dark mx-2 border-bottom pl-1">Birthday: {{ patient.Birthday }}</p>
                    <p class="card-text text-dark mx-2 border-bottom pl-1">Sex: {{ patient.get_Sex_display }}</p>
                    <p class="card-text text-dark mx-2 border-bottom pl-1">Adress: {{ patient.Adress }}</p>
                    <p class="card-text text-dark mx-2 border-bottom pl-1">Phone: {{ patient.Phone }}</p>

                </div>

                <div class="tab-content">
                    <div id="dia" class="tab-pane fade show active " role="tabpanel">
                        <table id="treatment_table" class="table table-striped table-bordered " cellspacing="0"
                               style="width:100%">
                            <thead>
                            <tr>
                                <a id="treatment_btn" href="" data-toggle="modal" data-target="#add_treatment"
                                   class="btn btn-primary btn-xs pull-left add-elem">Add new treatment
                                </a>
                                <th>Date</th>
                                <th>Name</th>
                                <th>Doctor</th>
                                <th>Note</th>
                                <th class="text-right">Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for treatment in listTre %}
                                <tr>
                                    <td>{{ treatment.Date }}</td>
                                    <td>{{ treatment.Name }}</td>
                                    <td>{{ treatment.Doctor }}</td>
                                    <td>{{ treatment.Note }}</td>
                                    <td class="td-actions text-right">
                                        <a class="btn btn-danger btn-just-icon btn-sm delete mr-2"
                                            href="{% url 'delete_treatment' patient.id user.login treatment.id %}">
                                            <i class="material-icons">close</i>
                                        </a>
                                        <a class="btn btn-info btn-just-icon btn-sm"
                                           href="{% url 'view_treatment' patient.id user.login treatment.id %}">
                                            <i class="material-icons">edit</i>
                                        </a>
                                    </td>
                                </tr>

                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>

            </div>


        </div>
    </div>


    <form id="form_add" class="add-form" data-db="records" method="POST">
        <div id="add_treatment" class="modal" tabindex="0" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Create treatment</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body container d-flex flex-column">
                        {% csrf_token %} 
                        {{ formTreatment }}
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Create</button>
                    </div>
                </div>
            </div>
        </div>
    </form>


    <script>
        $(document).ready(function() {
            $('#treatment_table').DataTable({
                "aLengthMenu": [
                    [5, 10, 25, -1],
                    [5, 10, 25, "All"]
                ]
            });

            $('#id_doctor').select2({
                dropdownParent: $("#add_treatment")
            });
        });



    </script>
    <style>
        body.modal-open {
            overflow: auto;
        }

        body.modal-open[style] {
            padding-right: 0px !important;
        }

        .modal::-webkit-scrollbar {
            width: 0 !important;
            /*removes the scrollbar but still scrollable*/
            /* reference: http://stackoverflow.com/a/26500272/2259400 */
        }

        table {
            width: 100%;
        }

        #treatment_table_filter {
            float: right;
        }

        #treatment_table_paginate {
            float: right;
        }

        #treatment_table_length {
            float: left;
        }

        #treatment_table_length label {
            display: flex;
            flex-direction: row;
            justify-content: center;
            margin-top: 15px;
        }

        #treatment_table_length select {
            margin-left: 5px;
            margin-right: 5px;
        }

        #treatment_table_filter label {
            display: flex;
            flex-direction: row;
            justify-content: center;
            margin-top: 15px;
        }

        #treatment_table_filter input {
            margin-left: 10px;
        }

        .add-elem {
            margin-top: 10px;
        }

        .back-to-top {
            cursor: pointer;
            position: fixed;
            bottom: 20px;
            right: 20px;
            display: none;
        }
    </style>
{% endblock %}